### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by qsefthuopq** [blablubbabc/Billboards#1]
From two users:
1.A player has bought a billboard,but he can't change it with shift+right click in worldguard area

sorry,but you can't use that here
That server uses WorldGuard6.2.2 and Billboards2.0.1 version:1.12.2

 

2.Player get two sign when he texted / in the sign. Billboards2.0.1

**Comment by blablubbabc** [comment]
Sorry for the late reply.

1.) There is a config setting for whether other plugins which attempt to prevent sign editing (such as WorldGuard) should be bypassed. I released a new version which has this setting enabled by default now.
2.) Regarding your second issue, I am not able to repreoduce this and will need further information on how to reproduce this (eg. which plugins are involved and how they are set up). If you happen to still have this issue consider creating a new issue ticket. I will try to reply quicker the next time. ;)
